### ISSUE TITLE
the latest update takes me out of minecraft

### ISSUE THREAD

**Issue by slatanic** [TeamChocoQuest/ChocolateQuestRepoured#239] opened 2021-01-05 22:06 UTC
I install this latest update and when I advance a bit it takes me out of the game .... I did all the steps, I followed the registry change step by step, only in the settings I changed the ability to break blocks in the dungeons ...... ................ with the previous version there is no problem, but I updated it to this one and after a while it takes me out of the game ... ..... if someone It says how to send the crash tell me how to put it here

 

I have tried it in 3 different worlds and in all of them the same thing happens to me I advance a little and it takes me out of the game ...... and this did not happen until I updated the mod

I went back to the version that I had that worked for me and the same thing happens to me now

uninstall I installed minecraft from scratch to see if it solved it and it remains the same

and when I get out of the game I get this on the game screen
```
The game crashed whilst exception ticking world
Error: java.lang.IllegalStateException: TickNextTick list out of synch
Error code: -1
-----------------------------------------------------------------------------------------------------------------------------------------

**Comment by DerToaster98** [comment] 2021-01-05 22:17
This is 
1) Not properly reported. It isn't even clear if it is CQR, please use the issue template, for how to attach files to github => google
2) The crash report either isn't complete, or isn't a crash report at all. Nonetheless it doesn't contain useful information. 

You have one hour from now to correct this issue to a proper one. Otherwise this will be treated as spam

**Comment by DerToaster98** [comment] 2021-01-05 22:37
uhm so you edited your message, the report still isn't in the required form and there still is no trace of a proper crash report.

**Comment by slatanic** [comment] 2021-01-05 22:39
I am very sorry I do not know how to upload the crash ..... I do not know much about pc ......... there I deleted what I thought I was the error, but only to say that when updating the mod I spent all the time problem, being that I had no problem ..... I will try to find how the crash report is uploaded, but it all started when updating the mod

**Comment by DerToaster98** [comment] 2021-01-05 22:39
ye ye. I managed to reproduce it, fix will be applied with a future update

**Comment by slatanic** [comment] 2021-01-05 22:43
So with the next update the error will end, or is it my problem?

meanwhile I take out the mod to play? hopefully not, because it's a great mod

Sorry for such basic questions, but I am not understood on this

**Comment by DerToaster98** [comment] 2021-01-05 22:44
It seems to only occur on "old" worlds, new ones seem to behave just fine. So starting a new world could be an option

**Comment by slatanic** [comment] 2021-01-05 22:47
is that I tried it in 3 new worlds, I advance a little and it takes me out of nowhere and uninstalled and reinstalled minecraft and the problem continues

**Comment by DerToaster98** [comment] 2021-01-05 22:48
you don't seem to understand:
Old world = world that was used BEFORE the update

**Comment by slatanic** [comment] 2021-01-05 22:51
Sorry, I use the google translator and it translates more or less no more, that's why sometimes I don't understand what you write .......... but I tried it in the world I was playing ..... ..old world and I tried it in new worlds and it's exactly the same

**Comment by DerToaster98** [comment] 2021-01-05 23:08
Please try the following:
1) Close the entire game
2) Remove all mods but CQR and it's dependencies
3) delete the CQR folder AND the cqrepoured.cfg file inside your config folder
4) Start the game
5) Open up a world and try to reproduce the error

**Comment by slatanic** [comment] 2021-01-05 23:23
play minecraft only with the mod ..... I will eliminate CQR and cqr poured.cfg to see if it is oh no the mod that causes the problem

**Comment by DerToaster98** [comment] 2021-01-05 23:24
it definitely is CQR but those are normal steps to reproduce bugs

**Comment by slatanic** [comment] 2021-01-05 23:36
it is definitely the mod, it is only the only mod installed with llibrary ..... I don't know how to upload the report

**Comment by DerToaster98** [comment] 2021-01-05 23:37
(Like i said, it is clear that is cqr, no need to tell again).

Anyway, i figured that "RandomPatches" seems to patch this problem since it turns out to be a vanilla and forge bug, so install this and try to reproduce it again.

**Comment by slatanic** [comment] 2021-01-05 23:41
ok there I will try again and notice if the problem was corrected

**Comment by slatanic** [comment] 2021-01-05 23:52
It didn't work, it was going well but he took me out of the game again ...... I don't know how to upload the report

**Comment by slatanic** [comment] 2021-01-06 00:04
[crash-2021-01-05_20.46.08-server.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/5773202/crash-2021-01-05_20.46.08-server.txt)

**Comment by slatanic** [comment] 2021-01-06 02:37
sorry Meldexun .......... but I did not understand the link you just put, what does that mean?

**Comment by Meldexun** [comment] 2021-01-06 02:39
It's just a commit that references this issue. It basically just means that someone has changed something that has something to do with this issue. You can ignore it.

**Comment by slatanic** [comment] 2021-01-06 02:44
ah ok meanwhile remove the mod to play or reinstall it from scratch?

**Comment by Meldexun** [comment] 2021-01-06 03:09
Until a bugfix is released: Open the CQR config (either ingame or minecraft/config/cqrepoured.cfg file) and set 'advanced -> multithreadedDungeonPreparation' to false

**Comment by slatanic** [comment] 2021-01-06 03:37
puse multithreadedDungeonPreparation en falso y sigue igual,me saca del juego

**Comment by DerToaster98** [comment] 2021-01-06 11:19
Install this update, it should fix the problem 
[update](https://cq-repoured.net/beta-2-1/)

**Comment by slatanic** [comment] 2021-01-11 14:12
gracias derToaster98 lo probare

puedo cambiar a falso esto sin ningun problema???,es lo unico q toco en configuracion

# This enables the protection system. Set to false to disable it globally. Disabling this does not delete Protected Regions and instead just does not prevent the player from for example placing blocks.
        B:protectionSystemEnabled=true

**Comment by DerToaster98** [comment] 2021-01-11 14:26
Yes, but keep in mind that that will not prevent the creation of protected regions, it will only bypass the checks. 

I will close this issue. If you have questions and not bugs to report, please ask them on the discord.

**Closed by DerToaster98** 2021-01-11 14:26 UTC
Labels: Resolution: Completed, Status: Reproduced, Type: Bug, Waiting for feedback
