### ISSUE TITLE
Crash by ticking entity(?) bug

### ISSUE THREAD

**Issue by rlcraftisharder** [TeamChocoQuest/ChocolateQuestRepoured#155] opened 2020-03-17 20:16 UTC
**Describe the bug**
When fighting a CQR mob inside one of the CQR dungeons, a sudden crash preventing you to go back to the world, due to ticking entity.

**To Reproduce**
1. Go find a CQR dungeon or use a Dp (Dungeon Placer)
2. Let it generate
3. Fight a CQR mob part of this dungeon (or structure)
4. You get a crash preventing going back to the world, causes being CQR being suspected or none.

**Expected behavior**
To not crash when fighting a CQR mob and let me fight through the whole dungeon.

**Screenshots**
Sorry, no screenshots.

**Versions**
Chocolate Quest Repoured: 1.12.2-1.12.0A
Forge: 14.23.5.2847
Minecraft: 1.12.2

**Other**
Crash report:
[crash-2020-03-17_14.45.54-server.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4345625/crash-2020-03-17_14.45.54-server.txt)

Log file:
[latest.log](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4345629/latest.log)

Singleplayer/Multiplayer: Singleplayer
Other mods (that are necessary to produce the bug): n/a, just CQR
Other mods (that are also installed):

**Comment by DerToaster98** [comment] 2020-03-17 20:18
Will fix that today

**Comment by DerToaster98** [comment] 2020-03-17 20:29
Also this is probably caused by primitive mobs, not cqr alone

I will fix it though

**Comment by rlcraftisharder** [comment] 2020-03-17 20:53
I don't have primitive mobs.

**Comment by DerToaster98** [comment] 2020-03-17 20:55
then let me be exact: a mod made by daveyx0

**Comment by rlcraftisharder** [comment] 2020-03-17 20:57
The summoner mod IS made by daveyx0, who created Primitive Mobs.

**Comment by DerToaster98** [comment] 2020-03-17 20:59
then its that one, still: fix for this is underway

**Comment by N3rglaX** [comment] 2020-03-17 21:01
I have the summoner mod installed and the game never crashed for me.

**Comment by DerToaster98** [comment] 2020-03-17 21:03
it is caused randomly cause basically it happens when a mob gets attacked and searches for allies in range. if it finds a allied mob that is not an AbstractCQREntity it tries to cast it and fails which causes the crash, that actually works with every other mod and is a mistake by us forgetting to check things

**Comment by DerToaster98** [comment] 2020-03-17 21:05
will be fixed in next build

**Closed by DerToaster98** 2020-03-17 21:05 UTC
Labels: Type: Bug

**Comment by Meldexun** [comment] 2020-03-17 21:11
Until the next release you should be able to enter your world without crashing when switching to peaceful. And the crash will happen when a cqr mob is low, in combat, wants to drink a healing potion, >=5 mobs are in a 20 blocks radius and one of them is a none cqr mob that is a friend of the mob that wants to drink.
