### ISSUE TITLE
Question only

### ISSUE THREAD

**Issue by Kasia1403** [TeamChocoQuest/ChocolateQuestRepoured#299] opened 2021-11-25 13:32 UTC
# Configuration file - cqrepoured.cfg

general {

    advanced {
        # Enable/Disable loading and caching of structure files during startup.
        B:cacheStructureFiles=true

        # The maximum amount of files which will be cached.
        # Min: 1
        # Max: 16384
        I:cachedStructureFilesMaxAmount=256

        # The maximum amount of kilobytes which will be cached. Ram usage will be approximately x * 200 kilobytes. This was the result when caching multiple, differently sized structure files and thus might not be representative for your setup.
        # Min: 1
        # Max: 16384
        I:cachedStructureFilesMaxSize=256

        # When enabled when starting the game it checks all structure files and tries to update the deprecated ones.
        B:checkAndUpdateDeprecatedStructureFiles=true
        B:debugAI=true
        B:debugDungeonGen=true
        B:enableMaxDamageCaps=true

        # If enabled, a faction will consider you as ally when you are on a team with the same name as the faction.
        B:enableOldFactionMemberTeams=false

        # When enabled cqr mobs only take 50% damage from IceAndFire mobs and deal 200% damage against IceAndFire mobs.
        B:enableSpecialFeatures=true
        D:entityCountGrowPerPlayer=0.25

        # Min: 1.0
        # Max: 1.7976931348623157E308
        D:flyingCowardPenaltyDamage=10.0

        # When enabled and a flying entity is hit by a cqr lightning it gets extra damage.
        B:flyingCowardPenaltyEnabled=true
        I:generationLimit=20000

        # Min: 0
        # Max: 1024
        D:generationMinDistanceToOtherStructure=1024.0

        # Enable/Disable checking for nearby vanilla structures before spawning a dungeon.
        B:generationRespectOtherStructures=true

        # The amount of milliseconds each dungeon is allowed to consume per tick during generation.
        # Min: 1
        # Max: 1024
        I:generationSpeed=20

        # When disable all light updates are delayed until the dungeon is generated which is usually a lot faster. (When Phosphor is installed this has no effect and light updates are processed immediately)
        B:instantLightUpdates=true

        # Only render the nearest 'limitEntityRenderingCount' amount of CQR entities. Bosses will be rendered normally.
        B:limitEntityRendering=true

        # The maximum amount of entities that get rendered.
        # Min: 8
        # Max: 256
        I:limitEntityRenderingCount=64

        # Enable/Disable multithreaded dungeon preparation. When enabled the calculations to prepare a dungeon for generation are done on another thread.
        B:multithreadedDungeonPreparation=true

        # When enabled overwrites the amount of chunks a ticket can keep loaded when generating/exporting dungeons.
        B:overwriteForgeChunkLoadingLimit=false

        # When enabled, the number or health of enemies in a dungeon scales up in multiplayer by (player count in dungeon region -1) * entityCountGrowPerPlayer
        B:scaleEntitiesOnPlayerCount=false

        # Skip rendering of entities that are behind blocks/not visible. Bosses will be rendered normally. This might cause issues where a mob is partly behind a block and thus does not get rendered but it's usually not really noticable. This setting has no effect when Entity Culling is installed.
        B:skipHiddenEntityRendering=true

        # It raytraces from the eyes of the player to the eyes of the mob and the other way around. Then it compares the positions that were hit and only renders the entity when no block was hit or the distance between both points is lower than this setting. This setting has no effect when Entity Culling is installed.
        # Min: 0
        # Max: 256
        I:skipHiddenEntityRenderingDiff=16

        # Blocks which will be saved in an extra part when exporting a structure which otherwise might not be placed correctly.
        S:specialBlocks <
            minecraft:bed
            minecraft:wooden_door
            minecraft:spruce_door
            minecraft:birch_door
            minecraft:jungle_door
            minecraft:acacia_door
            minecraft:dark_oak_door
            minecraft:iron_door
            minecraft:piston
            minecraft:sticky_piston
            minecraft:piston_head
         >

        # Entities which will be exported despite the ignore entities checkbox being checked.
        S:specialEntities <
            minecraft:painting
            minecraft:item_frame
            minecraft:armor_stand
            minecraft:minecart
            minecraft:chest_minecart
            minecraft:furnace_minecart
            minecraft:tnt_minecart
            minecraft:hopper_minecart
            minecraft:boat
         >
        B:structureImportMode=true

        # If activated, it will try to avoid generating the same structure of a dungeon type again and again.
        B:tryPreventingDuplicateDungeons=true
    }

    bosses {
        B:antiCowardMode=true
        I:antiCowardRadius=16
        B:armorForTheWalkerKing=true
        B:blackListBossesFromIaFGorgonHead=true
        B:boarmageExplosionAreaDestroysTerrain=false
        B:boarmageExplosionRayDestroysTerrain=false
        B:calamityBlockEquipParticles=true

        # WARNING: This WILL affect every player on the server or your lan world! Changing this as a player on a server does not have any effect
        B:enableBossBars=true
        B:enableHealthRegen=true
        I:enderCalamityHealingCrystalAbsorbAmount=40

        # Controls the roundness of the ender-calamity's shield, has a massive impact on performance. The higher, the rounder
        I:enderCalamityShieldRoundness=32
        D:giantSpiderMaxHealByBite=8.0
        S:giantTortoiseHardBlocks <
            minecraft:obsidian
            minecraft:iron_block
            minecraft:bedrock
         >
        B:harderWalkerKing=false
        B:hotFireballsDestroyTerrain=false
        S:netherDragonBreakableBlocks <
        >
        B:netherDragonDestroysBlocks=false
        I:netherDragonLength=28
        I:netherDragonStageTwoFireballInterval=40
        I:netherDragonStageTwoSegmentHP=50
        D:pirateCaptainFleeCheckRadius=32.0
        B:preventBlockPlacingNearBosses=false
        B:thrownBlocksDestroyTerrain=false
        B:thrownBlocksGetPlaced=true
    }

    bossdamagecaps {
        B:enableDamageCapForBosses=true
        D:maxDamageInPercentOfMaxHP=0.10000000149011612
        D:maxUncappedDamage=30.0
    }

    dungeonprotection {
        # This is a global toggle for the options in the individual dungeon configs, enabling this here does not enable it in all dungeons! Please adjust the individual dungeon configs!
        B:enablePreventBlockBreaking=true

        # This is a global toggle for the options in the individual dungeon configs, enabling this here does not enable it in all dungeons! Please adjust the individual dungeon configs!
        B:enablePreventBlockPlacing=false

        # This is a global toggle for the options in the individual dungeon configs, enabling this here does not enable it in all dungeons! Please adjust the individual dungeon configs!
        B:enablePreventEntitySpawning=true

        # This is a global toggle for the options in the individual dungeon configs, enabling this here does not enable it in all dungeons! Please adjust the individual dungeon configs!
        B:enablePreventExplosionOther=true

        # This is a global toggle for the options in the individual dungeon configs, enabling this here does not enable it in all dungeons! Please adjust the individual dungeon configs!
        B:enablePreventExplosionTNT=true

        # This is a global toggle for the options in the individual dungeon configs, enabling this here does not enable it in all dungeons! Please adjust the individual dungeon configs!
        B:enablePreventFireSpreading=true
        B:preventBlockBreaking=true
        B:preventBlockPlacing=false
        B:preventEntitySpawning=true
        B:preventExplosionOther=true
        B:preventExplosionTNT=true
        B:preventFireSpreading=true

        # Blocks which will be breakable despite being protected by the protection system.
        S:protectionSystemBreakableBlockWhitelist <
            minecraft:mob_spawner
            minecraft:torch
            cqrepoured:unlit_torch
            cqrepoured:phylactery
            cqrepoured:force_field_nexus
         >

        # Blocks with a whitelisted material will be breakable despite being protected by the protection system.
        S:protectionSystemBreakableMaterialWhitelist <
            WATER
            LAVA
            PLANTS
            VINE
            FIRE
            CACTUS
            CAKE
            WEB
         >

        # This enables the protection system. Set to false to disable it globally. Disabling this does not delete Protected Regions and instead just does not prevent the player from for example placing blocks.
        B:protectionSystemEnabled=true

        # Blocks which will be placeable at positions protected by the protection system.
        S:protectionSystemPlaceableBlockWhitelist <
            minecraft:torch
            minecraft:fire
            cqrepoured:unlit_torch
         >

        # Blocks with a whitelisted material will be placeable at positions protected by the protection system.
        S:protectionSystemPlaceableMaterialWhitelist <
         >
    }

    general {
        D:damageBlockedByShield=12.0

        # Each entry represents one set of mobtypes per "ring"
        S:defaultInhabitantConfig <
            SKELETON
            ZOMBIE,MUMMY
            ILLAGER
            SPECTER
            MINOTAUR
         >

        # Min: 0.0
        # Max: 10.0
        D:densityBehindWallFactor=2.0
        I:dungeonSeparation=1000

        # Distance in chunks to the worlds spawn point in which no dungeons can generate.
        # Min: 0
        # Max: 1000
        I:dungeonSpawnDistance=1000

        # Enable/Disable dungeon generation in super flat worlds.
        B:dungeonsInFlat=true
        D:electricFieldEffectSpreadRange=4.0
        B:enableAprilFools=true
        B:enableSpeechBubbles=true
        S:entityFactionRelation <
            minecraft:enderman=ENDERMEN
            minecraft:endermite=ENDERMEN
            minecraft:villager=VILLAGERS
            minecraft:villager_golem=VILLAGERS
            minecraft:vindication_illager=ILLAGERS
            minecraft:evocation_illager=ILLAGERS
            minecraft:vex=ILLAGERS
            minecraft:zombie=UNDEAD
            minecraft:zombie_villager=UNDEAD
            minecraft:husk=UNDEAD
            minecraft:skeleton=UNDEAD
            minecraft:skeleton_horse=UNDEAD
            minecraft:stray=UNDEAD
            minecraft:spider=BEASTS
            minecraft:cave_spider=BEASTS
            minecraft:ender_dragon=DRAGONS
            iceandfire:dragonegg=DRAGONS
            iceandfire:firedragon=DRAGONS
            iceandfire:icedragon=DRAGONS
         >
        B:hookOnlyPullsSmallerEntities=false

        # Min: 1
        # Max: 27
        I:maxItemsPerLootChest=8

        # Min: 0
        # Max: 27
        I:minItemsPerLootChest=2
        B:mobsFromCQSpawnerDontDespawn=true
        B:moreDungeonsBehindWall=true
        I:overallDungeonChance=100
        B:preventOtherModLoot=true

        # Copies the default config files from the jar to the config folder (existing files will get replaced).
        B:reinstallDefaultConfigs=false

        # Setting this to true allows you to set min and max items per chest
        B:singleLootPoolPerLootTable=true

        # Min: 0
        # Max: 100
        I:spawnerActivationDistance=48

        # Min: 0
        # Max: 32
        I:supportHillWallSize=8
    }

    mobs {
        # Min: 0
        # Max: 128
        I:alertRadius=20
        B:armorShattersOnMobs=true

        # Enables the axe & shield mechanic from vanilla for CQR mobs with a shield
        B:blockCancelledByAxe=true

        # For every player after the first bosses will receive x percent less damage. bossDamageReduction = (1.0 - x) ^ (playerCount - 1)
        # Min: 0.0
        # Max: 0.5
        D:bossDamageReductionPerPlayer=0.25
        B:disableFirePanicAI=false

        # Every X blocks the mobs HP goes up by 10% of it's base health
        # Min: 1
        # Max: 100000
        I:distanceDivisor=1000

        # Min: 0.0
        # Max: 1.0
        D:dropDurabilityMaximum=0.5

        # Min: 0.0
        # Max: 1.0
        D:dropDurabilityMinimum=0.1

        # Min: 0.0
        # Max: 1.0
        D:dropDurabilityModalValue=0.25

        # Min: 0.0
        # Max: 1.0
        D:dropDurabilityStandardDeviation=0.05
        B:enableDamageCapForNonBossMobs=false
        B:enableEntityStrafing=false
        B:enableEntityStrafingBoss=false
        B:enableHealthChangeOnDistance=false

        # Min: 0.0
        # Max: 1.0
        D:entityStrafingSpeed=0.5

        # Min: 0.0
        # Max: 1.0
        D:entityStrafingSpeedBoss=0.5

        # Min: 0
        # Max: 128
        I:factionUpdateRadius=100

        # Min: 2
        # Max: 64
        I:looterAIChestSearchRange=16
        I:looterAIStealableItems=4
        D:maxUncappedDamageForNonBossMobs=50.0
        D:maxUncappedDamageInMaxHPPercent=1.0

        # Min: 1
        # Max: 100000
        I:mobTypeChangeDistance=1500
        B:offhandPotionsAreSingleUse=true
    }

    wall {
        # Min: 0
        # Max: 1000
        I:distance=500
        B:enabled=true
        S:mob=cqrepoured:spectre
        B:obsidianCore=true

        # Min: 80
        # Max: 240
        I:topY=140

        # Min: 0
        # Max: 10
        I:towerDistance=3
    }

    materials {
        I:armorStatBackpackBase=3
        I:armorStatBullBase=7
        I:armorStatCloudBase=9
        I:armorStatDragonBase=9
        I:armorStatHeavyDiamondBase=9
        I:armorStatHeavyIronBase=8
        I:armorStatInquisitionBase=8
        I:armorStatKingCrownBase=9
        I:armorStatSlimeBase=6
        I:armorStatSpiderBase=7
        I:armorStatTurtleBase=8
        D:bullBattleAxeDamage=5.0
        I:bullBattleAxeDurability=1560
        D:bullBattleAxeEfficiency=0.0
        I:bullBattleAxeEnchantability=10
        I:bullBattleAxeHarvestLevel=0
        D:bullGreatSwordDamage=5.0
        I:bullGreatSwordDurability=1560
        D:bullGreatSwordEfficiency=0.0
        I:bullGreatSwordEnchantability=10
        I:bullGreatSwordHarvestLevel=0
        D:diamondDaggerDamage=1.5
        I:diamondDaggerDurability=1560
        D:diamondDaggerEfficiency=0.0
        I:diamondDaggerEnchantability=10
        I:diamondDaggerHarvestLevel=0
        D:diamondGreatSwordDamage=5.0
        I:diamondGreatSwordDurability=1560
        D:diamondGreatSwordEfficiency=0.0
        I:diamondGreatSwordEnchantability=10
        I:diamondGreatSwordHarvestLevel=0
        D:diamondSpearDamage=3.0
        I:diamondSpearDurability=1560
        D:diamondSpearEfficiency=0.0
        I:diamondSpearEnchantability=10
        I:diamondSpearHarvestLevel=0
        D:ironDaggerDamage=0.5
        I:ironDaggerDurability=250
        D:ironDaggerEfficiency=0.0
        I:ironDaggerEnchantability=14
        I:ironDaggerHarvestLevel=0
        D:ironGreatSwordDamage=4.0
        I:ironGreatSwordDurability=250
        D:ironGreatSwordEfficiency=0.0
        I:ironGreatSwordEnchantability=14
        I:ironGreatSwordHarvestLevel=0
        D:ironSpearDamage=2.0
        I:ironSpearDurability=250
        D:ironSpearEfficiency=0.0
        I:ironSpearEnchantability=7
        I:ironSpearHarvestLevel=0
        D:monkingDaggerDamage=2.5
        I:monkingDaggerDurability=1560
        D:monkingDaggerEfficiency=0.0
        I:monkingDaggerEnchantability=10
        I:monkingDaggerHarvestLevel=0
        D:monkingGreatSwordDamage=5.0
        I:monkingGreatSwordDurability=1560
        D:monkingGreatSwordEfficiency=0.0
        I:monkingGreatSwordEnchantability=10
        I:monkingGreatSwordHarvestLevel=0
        D:moonlightDamage=3.0
        I:moonlightDurability=2048
        D:moonlightEfficiency=0.0
        I:moonlightEnchantability=10
        I:moonlightHarvestLevel=0
        D:musketDiamondDamage=1.0
        I:musketDiamondDurability=300
        D:musketDiamondEfficiency=0.0
        I:musketDiamondEnchantability=10
        I:musketDiamondHarvestLevel=0
        D:musketIronDamage=0.0
        I:musketIronDurability=300
        D:musketIronEfficiency=0.0
        I:musketIronEnchantability=14
        I:musketIronHarvestLevel=0
        D:musketMonkingDamage=3.0
        I:musketMonkingDurability=300
        D:musketMonkingEfficiency=0.0
        I:musketMonkingEnchantability=10
        I:musketMonkingHarvestLevel=0
        D:ninjaDaggerDamage=2.5
        I:ninjaDaggerDurability=2048
        D:ninjaDaggerEfficiency=0.0
        I:ninjaDaggerEnchantability=10
        I:ninjaDaggerHarvestLevel=0
        D:spiderSwordDamage=3.0
        I:spiderSwordDurability=2048
        D:spiderSwordEfficiency=0.0
        I:spiderSwordEnchantability=10
        I:spiderSwordHarvestLevel=0
        D:sunshineDamage=3.0
        I:sunshineDurability=2048
        D:sunshineEfficiency=0.0
        I:sunshineEnchantability=10
        I:sunshineHarvestLevel=0
        D:toughnessStatBackpack=0.0
        D:toughnessStatBull=1.0
        D:toughnessStatCloud=1.0
        D:toughnessStatDragon=1.0
        D:toughnessStatHeavyDiamond=4.0
        D:toughnessStatHeavyIron=2.0
        D:toughnessStatInquisition=1.0
        D:toughnessStatKingCrown=0.5
        D:toughnessStatSlime=1.0
        D:toughnessStatSpider=1.0
        D:toughnessStatTurtle=1.0
        D:turtleSwordDamage=3.0
        I:turtleSwordDurability=2048
        D:turtleSwordEfficiency=0.0
        I:turtleSwordEnchantability=10
        I:turtleSwordHarvestLevel=0
        D:walkerSwordDamage=3.0
        I:walkerSwordDurability=2048
        D:walkerSwordEfficiency=0.0
        I:walkerSwordEnchantability=10
        I:walkerSwordHarvestLevel=0

        armormaterials {

            backpack {
                I:durability=67
                I:enchantability=5
                I:reductionAmounts <
                    1
                    3
                    4
                    1
                 >
                D:toughness=0.0
            }

            bull {
                I:durability=38
                I:enchantability=10
                I:reductionAmounts <
                    2
                    5
                    7
                    2
                 >
                D:toughness=1.0
            }

            cloud {
                I:durability=20
                I:enchantability=10
                I:reductionAmounts <
                    4
                    7
                    9
                    4
                 >
                D:toughness=1.0
            }

            dragon {
                I:durability=87
                I:enchantability=10
                I:reductionAmounts <
                    4
                    7
                    9
                    4
                 >
                D:toughness=1.0
            }

            heavydiamond {
                I:durability=82
                I:enchantability=10
                I:reductionAmounts <
                    4
                    7
                    9
                    4
                 >
                D:toughness=4.0
            }

            heavyiron {
                I:durability=74
                I:enchantability=9
                I:reductionAmounts <
                    3
                    6
                    8
                    3
                 >
                D:toughness=2.0
            }

            inquisition {
                I:durability=38
                I:enchantability=10
                I:reductionAmounts <
                    3
                    6
                    8
                    3
                 >
                D:toughness=1.0
            }

            kingcrown {
                I:durability=10
                I:enchantability=25
                I:reductionAmounts <
                    4
                    7
                    9
                    4
                 >
                D:toughness=0.5
            }

            slime {
                I:durability=38
                I:enchantability=10
                I:reductionAmounts <
                    1
                    4
                    6
                    1
                 >
                D:toughness=1.0
            }

            spider {
                I:durability=38
                I:enchantability=10
                I:reductionAmounts <
                    2
                    5
                    7
                    2
                 >
                D:toughness=1.0
            }

            turtle {
                I:durability=38
                I:enchantability=10
                I:reductionAmounts <
                    3
                    6
                    8
                    3
                 >
                D:toughness=1.0
            }

        }

        toolmaterials {
            D:daggerAttackDamageBonus=-1.0
            D:daggerAttackSpeedBonus=0.4
            D:daggerMovementSpeedBonus=0.05
            D:greatSwordAttackDamageBonus=3.0
            D:greatSwordAttackSpeedBonus=-0.4
            D:spearAttackDamageBonus=1.0
            D:spearAttackSpeedBonus=-0.1
            D:spearReachDistanceBonus=1.0

            bull {
                D:damage=5.0
                D:efficiency=0.0
                I:enchantability=10
                I:harvestLevel=0
                I:maxUses=1561
            }

            monking {
                D:damage=5.0
                D:efficiency=0.0
                I:enchantability=10
                I:harvestLevel=0
                I:maxUses=1561
            }

            moonlight {
                D:damage=5.0
                D:efficiency=0.0
                I:enchantability=10
                I:harvestLevel=0
                I:maxUses=2048
            }

            ninja {
                D:damage=5.0
                D:efficiency=0.0
                I:enchantability=10
                I:harvestLevel=0
                I:maxUses=2048
            }

            spider {
                D:damage=5.0
                D:efficiency=0.0
                I:enchantability=10
                I:harvestLevel=0
                I:maxUses=2048
            }

            sunshine {
                D:damage=5.0
                D:efficiency=0.0
                I:enchantability=10
                I:harvestLevel=0
                I:maxUses=2048
            }

            turtle {
                D:damage=5.0
                D:efficiency=0.0
                I:enchantability=10
                I:harvestLevel=0
                I:maxUses=2048
            }

            walker {
                D:damage=5.0
                D:efficiency=0.0
                I:enchantability=10
                I:harvestLevel=0
                I:maxUses=2048
            }

        }

    }

    basehealths {
        # Min: 1.0
        # Max: 1000.0
        D:AbyssWalker=40.0

        # Min: 1.0
        # Max: 1000.0
        D:AbyssWalkerKing=300.0

        # Min: 1.0
        # Max: 1000.0
        D:Boarmage=250.0

        # Min: 1.0
        # Max: 1000.0
        D:Boarman=25.0

        # Min: 1.0
        # Max: 1000.0
        D:Dummy=1.0

        # Min: 1.0
        # Max: 1000.0
        D:Dwarf=30.0

        # Min: 1.0
        # Max: 1000.0
        D:EnderCalamity=300.0

        # Min: 1.0
        # Max: 1000.0
        D:Enderman=40.0

        # Min: 1.0
        # Max: 1000.0
        D:Exterminatior=200.0

        # Min: 1.0
        # Max: 1000.0
        D:GiantSpider=150.0

        # Min: 1.0
        # Max: 1000.0
        D:GiantTortoise=400.0

        # Min: 1.0
        # Max: 1000.0
        D:Goblin=20.0

        # Min: 1.0
        # Max: 1000.0
        D:Golem=40.0

        # Min: 1.0
        # Max: 1000.0
        D:Gremlin=30.0

        # Min: 1.0
        # Max: 1000.0
        D:Human=20.0

        # Min: 1.0
        # Max: 1000.0
        D:Illager=25.0

        # Min: 1.0
        # Max: 1000.0
        D:Lich=200.0

        # Min: 1.0
        # Max: 1000.0
        D:Mandril=30.0

        # Min: 1.0
        # Max: 1000.0
        D:Minotaur=30.0

        # Min: 1.0
        # Max: 1000.0
        D:Mummy=20.0

        # Min: 1.0
        # Max: 1000.0
        D:NPC=20.0

        # Min: 1.0
        # Max: 1000.0
        D:Necromancer=150.0

        # Min: 1.0
        # Max: 1000.0
        D:NetherDragon=250.0

        # Min: 1.0
        # Max: 1000.0
        D:Ogre=35.0

        # Min: 1.0
        # Max: 1000.0
        D:Orc=30.0

        # Min: 1.0
        # Max: 1000.0
        D:Pirate=25.0

        # Min: 1.0
        # Max: 1000.0
        D:PirateCaptain=200.0

        # Min: 1.0
        # Max: 1000.0
        D:Skeleton=20.0

        # Min: 1.0
        # Max: 1000.0
        D:Spectre=30.0

        # Min: 1.0
        # Max: 1000.0
        D:Triton=30.0

        # Min: 1.0
        # Max: 1000.0
        D:Zombie=25.0
    }

}

**Comment by DerToaster98** [comment] 2021-11-25 13:40
Ok, so you leanred how to copy the content of the config file into the github issue...

First: Please **DO NOT** just post a file's content in the issues, either upload the file or use pastebin (or similar)
Second: What do you even want? The title is just "Question only" and the content of the issue is just our main config.

If you have questions: Ask them on the discord and not in the issue tracker (!). The issue tracker is for bugs and suggestions only, and everything there that does not fall in that category and does not use the corresponding templates will be closed instantly and ignored.

**Closed by DerToaster98** 2021-11-25 13:40 UTC
Labels: Type: Bug

**Comment by Kasia1403** [comment] 2021-11-26 10:10
So I have a suggestion: to add an setting for enabling and disabling individual mobs and structures for example Nether Dragon which probably is the cause of my crash. If my suggestion should not be here then please give me a link to where it should be.

**Comment by DerToaster98** [comment] 2021-11-26 10:28
If you have a question or suggestion: For questions: please ask them on the discord and not here.

Suggestions *can* be posted here or on the discord. If you post them here, then please use the template and don't just delete everything on it.

On your question: First, the nether dragon does not spawn anywhere (yet).
Structures can be disabled, please read the wiki.
