### ISSUE TITLE
Loot tables causing dimension load time increase.

### ISSUE THREAD

**Issue by Zilacon** [TeamChocoQuest/ChocolateQuestRepoured#247] opened 2021-01-27 19:06 UTC
**Common sense Info**
 - I play...
   - [X] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x] Singleplayer
   - [x] Multiplayer
 - [ ] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [ ] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x] I read through the FAQ and i could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
 
Versions
Chocolate Quest Repoured: 2.2.1B
Forge: 2846
Minecraft: 1.12.2
Modpack: Hexxit Updated 1.3 (CurseForge)

**Describe the bug**
When loading worlds for the server the mod is looking for loot table files for every dimension which do not exist. This causes hundreds of lines of errors/warnings in the console in total for all dimensions loaded, and also massively delays the start up of the server with many dimensions. Each dimension takes around 5 seconds to load each. There is no loot tables in any world files as far as i could see, not even the overworld. The only loot files are in the config/CQR folder.

**Expected behavior**
Mod finding the correct loot table configs or other files, and not delaying the loading of other dimensions.

**Other**
Full server start log: https://gist.github.com/Zilacon/bd53709666caf6531d5a8e4c800e3c32

**Comment by Meldexun** [comment] 2021-01-27 19:57
I guess your server software is the cause of the log getting spammed.
And (as I already stated in #246) there is no indication that trying to load the missing loot tables takes ~5 seconds.

Though you could create loot table files yourself. An Example:
Create the file: `world/data/loot_tables/cqrepoured/entities/mounts/pollo.json` and put this `{}` inside the file.
Do this for every missing warning (maybe you have to copy these files into every `world/data/dim-1/loot_tables` folder because of your server software or something). Then the warnings should be gone.

**Comment by Zilacon** [comment] 2021-01-27 20:08
Looks like it is generating files in the world folders, but its 1 directory off.
![Screenshot_963](https://user-images.githubusercontent.com/3002248/106047245-36770f80-6098-11eb-832b-34f3b8d2d558.png)
![Screenshot_962](https://user-images.githubusercontent.com/3002248/106047248-370fa600-6098-11eb-9147-f91299bcf7c1.png)

So in every non overworld dimension theres a folder with the same name as the dimension instead of inserting it into the DIM/data its going into DIM/DIM/data.

**Comment by Meldexun** [comment] 2021-01-27 21:42
And that changes what?

**Comment by Meldexun** [comment] 2021-01-27 23:13
So have/will you test it? Otherwise I would probably close this issue.

**Comment by Zilacon** [comment] 2021-01-27 23:17
I put the files exactly to the path you said and it still cant find them in all folders.

**Comment by Meldexun** [comment] 2021-01-27 23:49
So what does the log say? Does it still show the warning for all dimensions? Or maybe for all except the overworld?

Also did you put the files into every dimension data folder? Like do you have these files:
`world/data/loot_tables/cqrepoured/entities/mounts/pollo.json`
`world/DIM-1/data/loot_tables/cqrepoured/entities/mounts/pollo.json`
`world/DIM1/data/loot_tables/cqrepoured/entities/mounts/pollo.json`
...
Because you probably have to do this because of your server software.

**Comment by Zilacon** [comment] 2021-01-28 00:08
Sorry, i was under the assumption these files already were in the config files. Ive made them myself now and the warnings are gone now, and the dimensions are loading quickly now as well. Also they were missing from the overworld as well.

Thanks.
What do i do about the dim/dim/data folders/files though? Shouldn't those be in dim/data?

**Comment by Meldexun** [comment] 2021-01-28 00:27
> What do i do about the dim/dim/data folders/files though? Shouldn't those be in dim/data?
Don't use magma. Or open an issue on their end.
But you can probably just ignore it. The only thing that will happen is if you load that world without magma then cqr won't find these files.

Also can you upload a new log file? I'm just interested in how it looks now.

**Comment by Zilacon** [comment] 2021-01-28 01:00
Well, i switched from magma in june because of many issues to catserver. I switched back recently thinking all of those problems were fixed by now (like not able to enter the end at all). All of its still broken, so i switched back to catserver again today.

And its not really an option to NOT use these servers as all of my networks custom plugins is based off spigot/bukkit.
Heres the new log:
```
[16:05:54] [Server thread/INFO]: Loading dimension 0 (Survival) (net.minecraft.server.dedicated.DedicatedServer@e484b132)
[16:05:54] [Server thread/INFO]: Loaded 1590 advancements
[16:05:55] [Server thread/INFO]: Loaded 85 parts to generate
[16:05:55] [Server thread/INFO]: Loading dimension 1 (DIM1) (net.minecraft.server.dedicated.DedicatedServer@e484b132)
[16:05:55] [Server thread/INFO]: Loaded 0 parts to generate
[16:05:55] [Server thread/INFO]: Loading dimension 50 (DIM50) (net.minecraft.server.dedicated.DedicatedServer@e484b132)
[16:05:56] [Server thread/INFO]: Loaded 0 parts to generate
[16:05:56] [Server thread/INFO]: Loading dimension 51 (DIM51) (net.minecraft.server.dedicated.DedicatedServer@e484b132)
[16:05:56] [Server thread/INFO]: Loaded 0 parts to generate
[16:05:56] [Server thread/INFO]: Loading dimension 52 (DIM52) (net.minecraft.server.dedicated.DedicatedServer@e484b132)
[16:05:56] [Server thread/INFO]: Loaded 0 parts to generate
[16:05:56] [Server thread/INFO]: Loading dimension 53 (DIM53) (net.minecraft.server.dedicated.DedicatedServer@e484b132)
[16:05:56] [Server thread/INFO]: Loaded 0 parts to generate
[16:05:56] [Server thread/INFO]: Loading dimension 800 (DIM800) (net.minecraft.server.dedicated.DedicatedServer@e484b132)
[16:05:57] [Server thread/INFO]: Loaded 0 parts to generate
[16:05:57] [Server thread/INFO]: Loading dimension 801 (DIM801) (net.minecraft.server.dedicated.DedicatedServer@e484b132)
[16:05:57] [Server thread/INFO]: Loaded 0 parts to generate
[16:05:57] [Server thread/INFO]: Loading dimension 802 (DIM802) (net.minecraft.server.dedicated.DedicatedServer@e484b132)
[16:05:57] [Server thread/INFO]: Loaded 0 parts to generate
[16:05:57] [Server thread/INFO]: Loading dimension 803 (DIM803) (net.minecraft.server.dedicated.DedicatedServer@e484b132)
[16:05:57] [Server thread/INFO]: Loaded 0 parts to generate
[16:05:57] [Server thread/INFO]: Loading dimension 804 (DIM804) (net.minecraft.server.dedicated.DedicatedServer@e484b132)
[16:05:58] [Server thread/INFO]: Loaded 0 parts to generate
[16:05:58] [Server thread/INFO]: Loading dimension 805 (DIM805) (net.minecraft.server.dedicated.DedicatedServer@e484b132)
[16:05:58] [Server thread/INFO]: Loaded 0 parts to generate
[16:05:58] [Server thread/INFO]: Loading dimension 806 (DIM806) (net.minecraft.server.dedicated.DedicatedServer@e484b132)
[16:05:58] [Server thread/INFO]: Loaded 0 parts to generate
[16:05:58] [Server thread/INFO]: Loading dimension 807 (DIM807) (net.minecraft.server.dedicated.DedicatedServer@e484b132)
[16:05:58] [Server thread/INFO]: Loaded 0 parts to generate
[16:05:59] [Server thread/INFO]: Loading dimension 808 (DIM808) (net.minecraft.server.dedicated.DedicatedServer@e484b132)
[16:05:59] [Server thread/INFO]: Loaded 0 parts to generate
[16:05:59] [Server thread/INFO]: Loading dimension 809 (DIM809) (net.minecraft.server.dedicated.DedicatedServer@e484b132)
[16:05:59] [Server thread/INFO]: Loaded 0 parts to generate
[16:05:59] [Server thread/INFO]: Loading dimension 810 (DIM810) (net.minecraft.server.dedicated.DedicatedServer@e484b132)
[16:06:01] [Server thread/INFO]: Loaded 0 parts to generate
[16:06:01] [Server thread/INFO]: Loading dimension 811 (DIM811) (net.minecraft.server.dedicated.DedicatedServer@e484b132)
[16:06:02] [Server thread/INFO]: Loaded 0 parts to generate
[16:06:02] [Server thread/INFO]: Loading dimension 812 (DIM812) (net.minecraft.server.dedicated.DedicatedServer@e484b132)
[16:06:02] [Server thread/INFO]: Loaded 0 parts to generate
[16:06:02] [Server thread/INFO]: Loading dimension 813 (DIM813) (net.minecraft.server.dedicated.DedicatedServer@e484b132)
[16:06:02] [Server thread/INFO]: Loaded 0 parts to generate
[16:06:02] [Server thread/INFO]: Loading dimension 814 (DIM814) (net.minecraft.server.dedicated.DedicatedServer@e484b132)
[16:06:02] [Server thread/INFO]: Loaded 0 parts to generate
[16:06:02] [Server thread/INFO]: Loading dimension 815 (DIM815) (net.minecraft.server.dedicated.DedicatedServer@e484b132)
[16:06:03] [Server thread/INFO]: Loaded 0 parts to generate
[16:06:03] [Server thread/INFO]: Loading dimension 816 (DIM816) (net.minecraft.server.dedicated.DedicatedServer@e484b132)
[16:06:03] [Server thread/INFO]: Loaded 0 parts to generate
[16:06:03] [Server thread/INFO]: Loading dimension 817 (DIM817) (net.minecraft.server.dedicated.DedicatedServer@e484b132)
[16:06:03] [Server thread/INFO]: Loaded 0 parts to generate
[16:06:03] [Server thread/INFO]: Loading dimension 818 (DIM818) (net.minecraft.server.dedicated.DedicatedServer@e484b132)
[16:06:03] [Server thread/INFO]: Loaded 0 parts to generate
[16:06:03] [Server thread/INFO]: Loading dimension 819 (DIM819) (net.minecraft.server.dedicated.DedicatedServer@e484b132)
[16:06:03] [Server thread/INFO]: Loaded 0 parts to generate
[16:06:04] [Server thread/INFO]: Loading dimension 820 (DIM820) (net.minecraft.server.dedicated.DedicatedServer@e484b132)
[16:06:04] [Server thread/INFO]: Loaded 0 parts to generate
[16:06:04] [Server thread/INFO]: Loading dimension 821 (DIM821) (net.minecraft.server.dedicated.DedicatedServer@e484b132)
[16:06:04] [Server thread/INFO]: Loaded 0 parts to generate
[16:06:04] [Server thread/INFO]: Loading dimension -1 (DIM-1) (net.minecraft.server.dedicated.DedicatedServer@e484b132)
[16:06:04] [Server thread/INFO]: Loaded 0 parts to generate
[16:06:04] [Server thread/INFO]: Loading dimension 66 (DIM66) (net.minecraft.server.dedicated.DedicatedServer@e484b132)
[16:06:05] [Server thread/INFO]: Loaded 0 parts to generate
[16:06:05] [Server thread/INFO]: Loading dimension 20 (DIM20) (net.minecraft.server.dedicated.DedicatedServer@e484b132)
[16:06:05] [Server thread/INFO]: Loaded 0 parts to generate
[16:06:05] [Server thread/INFO]: Loading dimension 4 (DIM4) (net.minecraft.server.dedicated.DedicatedServer@e484b132)
[16:06:05] [Server thread/INFO]: Loaded 0 parts to generate
```

**Comment by Meldexun** [comment] 2021-01-28 01:26
Unless catserver is also changing minecraft causing the cqr files to be saved in the `world/DIM/DIM/data/CQR` folder then you would have to manually move the cqr files.
But unless you messed with the cqr configs the only really important information that is saved is about the protected regions. So maybe you don't care about that.

**Closed** 2021-01-29 05:26 UTC
Labels: Type: Bug
