### ISSUE TITLE
Dungeon crash my server

### ISSUE THREAD

**Issue by Rixxz287** [TeamChocoQuest/ChocolateQuestRepoured#361] opened 2022-07-24 06:41 UTC
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [ x ] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [ ] Singleplayer
   - [ x  ] Multiplayer
 - [ ] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [ ] I am using the latest version of the mod (all versions can be found on github under releases)
 - [ ] I read through the FAQ and I could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
**Describe the bug**
This is the crash report
I have a moded server and one castle crashed
some players can enter the server but other
are close to the castles enter and crashed the server

**To Reproduce**

1. Go to the snow and i see a castle and my server crash, only if u close to the structure all the other playes can play normaly but the server goes down when one player go to this place

**Screenshots**
 
**Versions (Note that 'latest' is NOT a valid version!**
Chocolate Quest Repoured: 1.12.2-2.6.10B i have all the dependens lasted versions 
Forge: 1.12.2 - 14.23.5.2860
Minecraft: 1.12.2 - 14.23.5.2860
Other mods (necessary to reproduce the bug):

**Log File**
Please use a paste site to upload the log file (for example https://gist.github.com/) and provide the link to the file here.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  ReachFixPlugin (ReachFix-1.12.2-1.0.5.jar)
  BCModPlugin (backpacks+1.12.2+-+3.5.12.jar)
  CQRPlugin (Chocolate_Quest_Repoured-1.12.2-2.6.10B.jar)
  BewitchmentFMLLoadingPlugin (bewitchment-1.12.2-0.0.22.64.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 7/24/22 12:50 AM
Description: Ticking entity

java.lang.UnsupportedOperationException: Attempted to call Event#setCanceled() on a non-cancelable event of type: net.minecraftforge.event.entity.EntityMobGriefingEvent
	at net.minecraftforge.fml.common.eventhandler.Event.setCanceled(Event.java:96)
	at team.cqr.cqrepoured.event.world.structure.protection.ProtectedRegionEventHandler.onMobGriefing(ProtectedRegionEventHandler.java:121)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_143_ProtectedRegionEventHandler_onMobGriefing_EntityMobGriefingEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.getMobGriefingEvent(ForgeEventFactory.java:815)
	at net.minecraft.entity.passive.EntityRabbit$AIRaidFarm.func_75250_a(EntityRabbit.java:554)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:94)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43)
	at net.minecraft.entity.passive.EntityRabbit.func_70636_d(EntityRabbit.java:274)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraftforge.fml.common.eventhandler.Event.setCanceled(Event.java:96)
	at team.cqr.cqrepoured.event.world.structure.protection.ProtectedRegionEventHandler.onMobGriefing(ProtectedRegionEventHandler.java:121)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_143_ProtectedRegionEventHandler_onMobGriefing_EntityMobGriefingEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.getMobGriefingEvent(ForgeEventFactory.java:815)
	at net.minecraft.entity.passive.EntityRabbit$AIRaidFarm.func_75250_a(EntityRabbit.java:554)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:94)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43)
	at net.minecraft.entity.passive.EntityRabbit.func_70636_d(EntityRabbit.java:274)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: minecraft:rabbit (net.minecraft.entity.passive.EntityRabbit)
	Entity ID: 271
	Entity Name: Rabbit
	Entity's Exact location: -9.50, 75.00, -227.50
	Entity's Block location: World: (-10,75,-228), Chunk: (at 6,4,12 in -1,-15; contains blocks -16,0,-240 to -1,255,-225), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['Rixxz2'/127, l='world', x=-169.35, y=113.12, z=-33.53]]
	Chunk stats: ServerChunkCache: 1241 Drop: 0
	Level seed: -1036028542119357563
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-160,64,248), Chunk: (at 0,4,8 in -10,15; contains blocks -160,0,240 to -145,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 312273 game time, 312273 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 19145 (now: false), thunder time: 2623 (now: true)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
... (79 líneas restantes)

**Comment by DerToaster98** [comment] 2022-07-24 07:25
Duplicate of #353 
And please DO NOT just paste the crashlog content here, upload it to a paste sute

**Closed by DerToaster98** 2022-07-24 07:25 UTC
Labels: Type: Bug

**Comment by DerToaster98** [comment] 2022-07-24 07:54
Fixed in 2.6.11B

**Comment by Rixxz287** [comment] 2022-07-25 23:35
> Fixed in 2.6.11B

bro u have discord ?

**Comment by DerToaster98** [comment] 2022-07-26 05:28
Please don't misuse the issue tracker and don't spam it with useless things.

Also please don't call me "bro", we're not related in any way.
