### ISSUE TITLE
Incompadability with Unloader mod

### ISSUE THREAD

**Issue by jamesbenbow97** [TeamChocoQuest/ChocolateQuestRepoured#199] opened 2020-06-16 04:13 UTC
**Common sense Info**
 - I play...
   - [x] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x] Singleplayer
   - [ ] Multiplayer
 - [x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [x] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured: A25.1
Forge: 14.23.5.2847
Minecraft: 1.12.2

**Describe the bug**
The game crashes a couple of seconds after world load, Unloder mod seems to affecting something despite only being in the overworld

**To Reproduce**
Start world
[crash-2020-06-16_13.54.26-server.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4784295/crash-2020-06-16_13.54.26-server.txt)

**Expected behavior**

**Screenshots**

**Other**
Please note: log files and crash reports should be uploaded as a FILE and not as a copy paste of the text of it here. Upload the file to a site like pastebin or similar and link it here!!
 - Link to Crash report file:
 - Link to Log file:
 - Other mods (that are necessary to produce the bug):
 - Other mods (that are also installed):
 - CQR config folder (link, only if you changed the configs):
 - Other mod's configs (link):

**Comment by DerToaster98** [comment] 2020-06-16 05:21
Could be fixed in the next build but to be honest that crash makes no sense at all.
The only way this crash can occur is if some mod (maybe Unloader, but i don't know for sure) plays around with CQR-internal memory, in detail a certain Map that holds the generation managers in relation to their "World" (every dimension is a world internally)

**Comment by DerToaster98** [comment] 2020-06-16 05:27
Also please try to reproduce that bug only with CQR, Unloader mod and their respective dependencies to verify that this is a problem with these two and not something else in the modpack

**Comment by Meldexun** [comment] 2020-06-16 10:13
The crash report is not enough. A log file would be useful.

**Comment by DerToaster98** [comment] 2020-06-23 19:30
Issue will be closed cause the issue reporter seems to be unwilling to cooperate, without cooperation we can't solve this issue.

**Closed by DerToaster98** 2020-06-23 19:30 UTC
Labels: Type: Bug
