### ISSUE TITLE
Shader crash on MacOS

### ISSUE THREAD

**Issue by Rubyz67** [TeamChocoQuest/ChocolateQuestRepoured#302] opened 2021-11-27 14:12 UTC
**Common sense Info**
To check a checkbox: Insert a lower case X between the square brackets, you need to remove the space though.
 - I play...
   - [x] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x] Singleplayer
   - [ ] Multiplayer
 - [x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x] I read through the FAQ and i could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [x] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured ('latest' IS NOT a valid version! Please use the version string that shows up in the mod overview of forge): beta 6.1
Forge: 14.23.5.2855
Minecraft: 1.12.2 

**Describe the bug**
The game crashes on start up

**To Reproduce**
1. press play
2. wait for loading
3. crash
.
.
.

**Expected behavior**
The Main Menu to appear for mc

**Screenshots**

**Other**
Please note: log files and crash reports should be uploaded as a FILE and not as a copy paste of the text of it here. Upload the file to a site like pastebin or similar and link it here!!
 - Link to Crash report file (only if the game crashes because of this bug, please use something like pastebin to upload it, then link it here): https://gist.github.com/Rubyz67/55a71f9e6cfc2617ddfe85dbbaeef0b8
 - Link to Log file (only if the game crashes because of this bug, please use something like pastebin to upload it, then link it here): 
 - Other mods (that are necessary to produce the bug): 1.12.2-RecipeScramble-2.8.5.jar
adminweapons-v3.4-mc1.12.jar
AoA3-3.3.6.jar
Aroma1997Core-1.12.2-2.0.0.2.jar
AromaBackup-1.12.2-2.1.1.4.jar
Avaritia-1.12.2-3.3.0.37-universal.jar
Avaritiaddons-1.12.2-1.3.jar
AvaritiaTweaks-1.12.2-1.3.jar
AvengersTech 4.3.jar
BattleTowers-1.12.2.jar
Baubles-1.12-1.5.2.jar
bettercaves-1.12.2-2.0.4.jar
BetterFps-1.4.8.jar
BetterMineshaftsForge-1.12.2-2.2.1.jar
BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar
Bloodmoon-MC1.12.2-1.5.3.jar
blue_skies-1.12.2-v1.1.3.jar
Bountiful Baubles-1.12.2-0.1.6.jar
branders-enhanced-mob-spawners-v1.12.2-1.4.4.jar.jar
BrandonsCore-1.12.2-2.4.20.162-universal.jar
castle_dungeons-2.2p1-1.12.2-forge.jar
ChanceCubes-1.12.2-5.0.2.385.jar
Chocolate_Quest_Repoured-1.12.2-2.6.1B.jar
Clumps-3.1.2.jar
CodeChickenLib-1.12.2-3.2.3.358-universal.jar
Controlling-3.0.10.jar
craftabletardisstuff-1.0.jar
CTM-MC1.12.2-1.0.2.31.jar
deuf-1.1-1.12.2.jar
DFHeroesExpansion 1.3(non restricted forge).jar
DimensionalEdibles-1.12.2-1.3.2.jar
DoomlikeDungeons-1.14.10-MC1.12.2.jar
Draconic-Additions-1.12.2-1.17.0.45-universal.jar
Draconic-Evolution-1.12.2-2.3.28.354-universal.jar
ElectroblobsWizardry-4.3.4-MC1.12.2.jar
EntityCulling-1.12.2-4.2.1.jar
Essential-Forge-1.12.2.jar
ExtraSpells-1.12.2-1.2.0.jar
extrautils2-1.12-1.9.9.jar
FastFurnace-1.12.2-1.3.1.jar
FastLeafDecay-v14.jar
FastWorkbench-1.12.2-1.7.3.jar
foamfix-0.10.14-1.12.2.jar
Forgelin-1.8.4.jar
FpsReducer-mc1.12.2-1.20.jar
ftb-ultimine-1202.3.5.jar
future-mc-1.12.2-0.2.7.4.jar
geckolib-forge-1.12.2-3.0.11.jar
Gobber-1.12.2_1.1.207.jar
GunpowderLib-1.12.2-1.1.jar
HeroesExpansion-1.12.2-1.3.5.jar
Hwyla-1.8.26-B41_1.12.2.jar
ICBM-classic-1.12.2-4.1.0b20211106011048.jar
iChunUtil-1.12.2-7.2.2.jar
ido-1.12.2-1.1.0.jar
IllagersPlus-1.12.2-1.1.3.jar
Infinity Armor 1.0.1.jar
infinity-1.12.jar
inventorypets-1.12-2.0.15.jar
IronBackpacks-1.12.2-3.0.8-12.jar
ironchest-1.12.2-7.0.72.847.jar
IronMan-1.12.2-Beta-1.12.2-1.2.6.jar
IvToolkit-1.3.3-1.12.jar
jei_1.12.2-4.16.1.301.jar
jeiintegration_1.12.2-1.6.0.jar
journeymap-1.12.2-5.7.1.jar
JustEnoughIDs-1.0.3-55.jar
keywizard-1.12.2-1.7.3.jar
kindredlegacy-1.12.2-1.2.1.jar
LibraryEx-1.12.2-1.2.2.jar
llibrary-1.7.20-1.12.2.jar
LucraftCore-1.12.2-2.4.16.jar
mdxlib-3.0.0.26.jar
memory_repo
MightyEnderChicken-1.12.2-7.3.0.jar
Minewatch-1.12.X-3.13.jar
ModifierKeyFix-1.0.jar
moreavaritia-mc1.12.2-v4.jar
MouseTweaks-2.10-mc1.12.2.jar
mowziesmobs-1.5.8.jar
MutantBeasts-1.12.2-1.0.2.jar
nanfix-final-absorbtion.jar
NetherEx-1.12.2-2.2.5.jar
NoMoreRecipeConflict-0.13(1.12.2).jar
Overloaded-1.12.2-0.0.59.jar
overloadedarmorbar-1.0.4g.jar
OverpoweredInventory-1.12-2.3.1.jar
Patchouli-1.0-23.6.jar
phosphor-1.12.2-0.2.6+build50-universal.jar
Placebo-1.12.2-1.6.0.jar
ProjectE-1.12.2-PE1.4.1.jar
ProjectEIntegration-1.12.2-2.3.1.jar
ProjectIntelligence-1.12.2-1.0.9.28-universal.jar
PymTech-1.12.2-1.0.2.jar
randompatches-1.12.2-1.22.1.10.jar
RandomThings-MC1.12.2-4.2.7.4.jar
rats-3.2.14-1.12.2.jar
RecurrentComplex-1.4.8.2.jar
RedstoneFlux-1.12-2.1.1.1-universal.jar
RoguelikeDungeonsFnarEdition-1.12.2-2.4.0.jar
Ruins-1.12.2.jar
savemystronghold-1.12.2-1.0.0.jar
ScalingHealth-1.12.2-1.3.42+147.jar
SilentLib-1.12.2-3.0.14+168.jar
simplegenerators-1.12.2-2.0.20.2.jar
spark-forge1122.jar
spectrite-1.7.1.jar
SpeedsterHeroes-1.12.2-2.2.1.jar
star-tech-1.1.1.jar
stg-1.12.2-1.2.3.jar
Surge-1.12.2-2.0.77.jar
tardis-0.1.4A.jar
techguns-1.12.2-2.0.2.0_pre3.2.jar
the-fifth-world-0.5.1.jar
TheAbyss 3.5.0LV 1.12.2.jar
TickrateChanger-1.0.14.jar
tombstone-4.5.1-1.12.2.jar
ToolBelt-1.12.2-1.9.14.jar
TravelersBackpack-1.12.2-1.0.35.jar
Trinkets and Baubles-0.31.jar
twilightforest-1.12.2-3.11.1020-universal[1].jar
valkyrielib-1.12.2-2.0.20.1.jar
VanillaFix-1.0.10-150.jar
WanionLib-1.12.2-2.5.jar
Wawla-1.12.2-2.6.275.jar
Waystones_1.12.2-4.1.0.jar
yoyos_1.12.2-1.3.3.25.jar
 - Other mods (that are also installed, at best: link a zip file that contains all the installed mods):
 - CQR config folder (link, only if you changed the configs):
 - Other mod's configs (link, only if any config was changed):

**Comment by DerToaster98** [comment] 2021-11-27 14:18
Please reproduce this with only cqr and it's dependencies

**Comment by Meldexun** [comment] 2021-11-27 14:27
We need the log to be able to resolve this issue.

**Comment by Rubyz67** [comment] 2021-11-28 15:08
[random.zip](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/7613773/random.zip)
here is the zip

**Comment by DerToaster98** [comment] 2021-11-28 15:12
we need the logfile, not your whole modpack. The problem is likely related to your hardware, so sending the modpack won't help

**Comment by WolfBV** [comment] 2021-12-01 02:04
Different person, same crash. https://pastebin.com/TfWN2T6b

**Comment by Meldexun** [comment] 2021-12-01 02:44
What is your cpu/gpu and what is your graphics driver version? Intel HD 4000 should support up to OpenGL 4.0 and CQR requires OpenGL 3.0. So updating your graphics driver should be enough.

**Comment by WolfBV** [comment] 2021-12-01 04:54
I think it might be something with GLSL, idk https://stackoverflow.com/questions/31803872/opengl-glsl-shaders-on-mac-does-not-compile

cpu is 2.5 GHz Intel Core i5. gpu is Intel HD Graphics 4000 1536 MB.

**Comment by WolfBV** [comment] 2021-12-01 05:33
Issue appears after the Beta 6.0 update.

**Comment by DerToaster98** [comment] 2021-12-01 06:24
> Issue appears after the Beta 6.0 update.

That is only logical cause that shader got added in 2.6.0B, it can't appear in lower versions.

**Comment by DerToaster98** [comment] 2021-12-01 06:39
Anyway, please try to update your graphics driver, even if the other person has a newer OS version. 

However, thanks for also reporting, the infos you gave us are useful

**Comment by Rubyz67** [comment] 2021-12-01 23:21
ty

**Comment by Rubyz67** [comment] 2021-12-01 23:23
my graphics Intel Iris Graphics 6100 1536 MB

**Comment by Rubyz67** [comment] 2021-12-01 23:24
it says i have support for open gl 2.1+

**Comment by xJon** [comment] 2021-12-09 19:15
We're also getting reports of crashes using the latest version of CQR: https://github.com/xJon/Hexxit-II/issues/77
Crash report: https://pastebin.com/pd7rz22y
Note that they're using `OpenGL: Apple M1 GL version 2.1 Metal - 76.1, Apple`.

**Comment by DerToaster98** [comment] 2021-12-09 19:17
We haven’t published the patch yet. Try updating your GPU drivers

**Comment by DerToaster98** [comment] 2021-12-09 19:19
Problem seems to be that the used GPUs (maybe in general on macos?) only support up to ogl 2.1. CQR requires at least 3.0.0

I‘m not an expert on that though

**Comment by DerToaster98** [comment] 2021-12-09 19:42
Like i said: i‘m not an expert in the topic of shaders. We have a fix though but the update is not ready

**Comment by sheepdoglord554** [comment] 2021-12-12 19:22
is there a quick fix for mac users on this?

**Comment by DerToaster98** [comment] 2021-12-12 19:24
The only thing you could do is
1) fix the shader for us
2) try updating your graphics card drivers

those are all your options

**Comment by sheepdoglord554** [comment] 2021-12-12 19:48
so this is actually an issue with the shader included in Hexxit, not Chocolate Quest?

**Comment by DerToaster98** [comment] 2021-12-12 19:53
The shader is part of CQ so no

**Comment by sheepdoglord554** [comment] 2021-12-12 20:25
Oh okay -- looks like my friend's graphics drivers are up to date so we'll have to wait on a DIX. Thanks!

**Comment by gascraft971** [comment] 2021-12-23 12:58
I'm pretty sure that graphics drivers on MacOS can't be updated, they are built into system updates.
The latest macOS Monterey 12.1 still hasn't fixed the issue for me (CQR is still crashing)

**Comment by sheepdoglord554** [comment] 2021-12-31 08:18
Any updates on this?

**Comment by CPlusPatch** [comment] 2021-12-31 09:04
It seems like someone will have to change the code to make it OSX-compatible, as it's just not possible to use OpenGL 3.0 on a Mac

https://stackoverflow.com/questions/41120025/isnt-it-possible-to-run-opengl-3-0-on-macbok-pro-2015-mid-with-glfw3

**Comment by DerToaster98** [comment] 2021-12-31 09:45
I think Meldex rewrote the shader to use openGL 1.1.

If you want to test it: Replace these files in the mod jar with these:
File path: `<Mod jar root>assets/cqrepoured/shaders/sphere/`
Files to replace: vertex.glsl, fragment.glsl

New files: f
ragment.glsl: https://raw.githubusercontent.com/TeamChocoQuest/ChocolateQuestRepoured/master/src/main/resources/assets/cqrepoured/shaders/sphere/fragment.glsl
vertex.glsl: https://raw.githubusercontent.com/TeamChocoQuest/ChocolateQuestRepoured/master/src/main/resources/assets/cqrepoured/shaders/sphere/vertex.glsl

**Comment by DerToaster98** [comment] 2021-12-31 09:45
If you can't do this wait for the next release

**Comment by DerToaster98** [comment] 2021-12-31 09:48
Please note that the solution provided above may rely on changes in the mod's program logic so it might not work or have consequences

**Comment by DerToaster98** [comment] 2022-01-01 14:24
This is potentially fixed in v2.6.3B, which was published yesterday

**Comment by DerToaster98** [comment] 2022-01-03 11:02
fixed in v2.6.3B

Reopen if it still crashes with the new update

**Closed by DerToaster98** 2022-01-03 11:02 UTC
Labels: Type: Bug
