### ISSUE TITLE
Walker King Crashes on  his Magic Casting

### ISSUE THREAD

**Issue by Yranic** [TeamChocoQuest/ChocolateQuestRepoured#179] opened 2020-04-23 09:39 UTC
The Walker King keeps crashing the game once he uses his different spells

**Versions**
Chocolate Quest Repoured:
Forge:14.23.5.2847
Minecraft:1.12.2

**Other**
Crash report:[crash-2020-04-23_11.32.04-server.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4521599/crash-2020-04-23_11.32.04-server.txt)

Log file:
Singleplayer
Other mods (that are necessary to produce the bug):
Idk
Other mods (that are also installed):
[1.12.2]DamageIndicatorsMod-3.5.1
Baubles-1.12-1.5.2
BetterFps-1.4.8
ChocolateQuestRepoured-1.12.2-1.15.1A
CTM-MC1.12.2-1.0.2.31
foamfix-0.10.10-1.12.2
iceandfire-1.9.0
InventoryTweaks-1.63
jei_1.12.2-4.15.0.291
llibrary-1.7.19-1.12.2
malisiscore-1.12.2-6.5.1
malisisdoors-1.12.2-7.3.0
Mapmaker's Gadgets-1.2_for_1.12.x
MobBattleMod-1.12.2-2.3.3
mowziesmobs-1.5.4
MutantBeasts-1.12.2-0.7.1
OptiFine_1.12.2_HD_U_F5
Welcome To The Jungle-1.2006.1222
worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist

**Comment by DerToaster98** [comment] 2020-04-23 09:53
that bug is a duplicate, cause isnt the walker king, will be fixed in a bugfix build later today
Duplicate of #178

**Comment by DerToaster98** [comment] 2020-04-23 19:17
should be fixed in newest build

**Closed by DerToaster98** 2020-04-23 19:17 UTC
Labels: Type: Duplicate
