### ISSUE TITLE
Spear Mouse Handler NPE Crash

### ISSUE THREAD

**Issue by mxnmnm** [TeamChocoQuest/ChocolateQuestRepoured#303] opened 2021-12-01 05:41 UTC
**Common sense Info**
To check a checkbox: Insert a lower case X between the square brackets, you need to remove the space though.
 - I play...
   - [x] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [ ] Singleplayer
   - [x] Multiplayer
 - [ ] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x] I read through the FAQ and i could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [x] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured ('latest' IS NOT a valid version! Please use the version string that shows up in the mod overview of forge): 2.6.2B
Forge: 2855
Minecraft: 1.12.2

**Describe the bug**
Crash related to spears despite me not using anything from the mod (maybe one of the mobs attacking me was? I was in the middle of an onslaught raid [custom made and I don't remember giving them weapons from this mod]

**To Reproduce**
It seems to happen when I'm killing mobs with a sword (I am in the middle of a custom onslaught raid [not using weapons from this mod]) 

**Expected behavior**
No crash

**Other**
Please note: log files and crash reports should be uploaded as a FILE and not as a copy paste of the text of it here. Upload the file to a site like pastebin or similar and link it here!!
 - Link to Crash report file (only if the game crashes because of this bug, please use something like pastebin to upload it, then link it here): https://gist.github.com/mxnmnm/3acd45f7f896650c4eafd557932d44f7

if you need more info let me know

**Comment by DerToaster98** [comment] 2021-12-01 06:35
First: Please reproduce that this issue is caused by our mod, you use a lot of additional mods that could cause it too.

It would also be good to know if one of the raid entities (or a different player) used a spear

**Comment by mxnmnm** [comment] 2021-12-01 22:34
None of them were holding spears as far as I know. I cannot reproduce it because it was only in a specific situation that kept crashing (which was resolved by not attacking and letting myself die). I should have made a backup, but it was in the heat of the moment and I wasn't thinking lol.

**Comment by DerToaster98** [comment] 2021-12-02 06:00
Uhm ok, we need to see if my workaround fixes it but it honestly makes no sense that it crashes that way

**Comment by mxnmnm** [comment] 2021-12-03 04:56
Well I'll be play testing my pack quite a bit, so if it comes up again we'll know that the workaround didn't work.

**Comment by mxnmnm** [comment] 2021-12-04 08:40
I managed to recreate it, so send me an updated version for testing :D

**Comment by DerToaster98** [comment] 2021-12-04 08:50
Will do later

**Comment by DerToaster98** [comment] 2021-12-04 10:47
Here's a build with a workaround in it, please test if it is fixed now

Test build: https://www.dropbox.com/s/hsns4qjybmowp73/Chocolate_Quest_Repoured-1.12.2-2.6.3B-PreRelease.jar?dl=0

**Comment by mxnmnm** [comment] 2021-12-05 09:39
It seems to be doing ok for now, but I might just test it on a server with my friend to see if it happens again, just to be safe. I'll update you after we've gone through a few raids with no issues.

**Comment by Tot7uafag** [comment] 2021-12-12 02:18
had this crash before, it happens when mobs use spears, specially ones from AW2

**Comment by Reveax** [comment] 2021-12-22 04:27
> Here's a build with a workaround in it, please test if it is fixed now
> 
> Test build: Taken down because people were downloading it too often!

Same problem here, is the build still available for download somewhere?

**Comment by DerToaster98** [comment] 2021-12-22 06:04
No, i took that build down cause people were reuploading it and distributing it

**Comment by DerToaster98** [comment] 2022-01-03 11:02
fixed in v2.6.3B

**Closed by DerToaster98** 2022-01-03 11:02 UTC
Labels: Type: Bug
