### ISSUE TITLE
Chocolate Quest Repoured Produces Compitability Error with Mac on Hexxiit 1.20

### ISSUE THREAD

**Issue by sheepdoglord554** [TeamChocoQuest/ChocolateQuestRepoured#305] opened 2021-12-12 04:52 UTC
**Common sense Info**
To check a checkbox: Insert a lower case X between the square brackets, you need to remove the space though.
 - I play...
   - [x] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x] Singleplayer
   - [x] Multiplayer
 - [x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x] I read through the FAQ and i could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [x] The game crashes because of this bug

**Describe the bug**

**To Reproduce**
1. Launch Hexxit 1.20 on Mac

**Expected behavior**
The game to successfully launch on Mac.

**Other**
Please note: log files and crash reports should be uploaded as a FILE and not as a copy paste of the text of it here. Upload the file to a site like pastebin or similar and link it here!!
 - Link to Crash report file (only if the game crashes because of this bug, please use something like pastebin to upload it, then link it here):
 - Link to Log file (only if the game crashes because of this bug, please use something like pastebin to upload it, then link it here): https://pastebin.com/ztMqrYEW
 - Other mods (that are necessary to produce the bug): Hexxit 1.20
 - Other mods (that are also installed, at best: link a zip file that contains all the installed mods): Hexxit 1.20
 - CQR config folder (link, only if you changed the configs):
 - Other mod's configs (link, only if any config was changed):

**Comment by DerToaster98** [comment] 2021-12-12 10:03
Duplicate of #302

**Closed by DerToaster98** 2021-12-12 10:03 UTC
Labels: Type: Bug
