### ISSUE TITLE
Nether Cities broken

### ISSUE THREAD

**Issue by LordEpos** [TeamChocoQuest/ChocolateQuestRepoured#104] opened 2020-01-01 01:48 UTC
Nether Cities don't generate in the world. There's an error in the console, though the game doesn't crash, which Izen recorded here: https://pastebin.com/dMqYNnBi

The spawning item also doesn't work.

**Comment by DerToaster98** [comment] 2020-01-01 11:27
Was related to an NPE caused by me forgetting to update stuff in the nether city....

Should be fixed now

**Closed by DerToaster98** 2020-01-01 11:27 UTC
Labels: Priority: High, Type: Bug
