### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by FanRenLa** [TeamChocoQuest/ChocolateQuestRepoured#357] opened 2022-07-15 09:28 UTC
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [ ] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [X] Singleplayer
   - [ ] Multiplayer
 - [ ] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [X] I am using the latest version of the mod (all versions can be found on github under releases)
 - [ ] I read through the FAQ and I could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [X] The game crashes because of this bug
 
**Describe the bug**
When exploring the world
**To Reproduce**
1. Go to ...When loading the world
2. Use item ...When spawning - Nether Dragon
3. Place block ...When using Dungeon Placer
4. ...The above conditions are all crashed separately

**Screenshots**
 
**Versions (Note that 'latest' is NOT a valid version!**
Chocolate Quest Repoured:Chocolate_Quest_Repoured-1.12.2-2.6.10B
Forge:2860
Minecraft:1.12.2
Other mods (necessary to reproduce the bug):OptiFine_1.12.2_HD_U_G5

**Log File**
Please use a paste site to upload the log file (for example https://gist.github.com/) and provide the link to the file here.
https://gist.github.com/FanRenLa/a075b35b203f4df37e5b1d159c09e212

**Comment by DerToaster98** [comment] 2022-07-15 09:31
Duplicate of #353 

Already fixed in development, will be patched at some point

**Comment by DerToaster98** [comment] 2022-07-24 07:54
Fixed in 2.6.11B

**Closed by DerToaster98** 2022-07-24 07:54 UTC
Labels: Type: Bug, Type: Duplicate
