### ISSUE TITLE
Not compatible with biomes o'plenty

### ISSUE THREAD

**Issue by ZR-pl** [TeamChocoQuest/ChocolateQuestRepoured#188] opened 2020-05-03 09:50 UTC
**Describe the bug**
I have a modpack with 43 mods. I added CQR and went in the nether. The custom nether biomes added by BOP were broken. There wouldn't be anything other than the ground level of the biome for example there wasn't any tall grass or trees where they were supposed to be and sometimes but rarely there were structures from the ruins mod than normally spawn only in the overworld. I have a screenshot of that. I have llibrary.

**To Reproduce**
1. Go to the nether with BOP installed.

.
.
.

**Expected behavior**
Biomes should generate the right way.
**Screenshots**

![Corrupted sands biome](https://user-images.githubusercontent.com/63923047/80911053-0894b280-8d34-11ea-8ab5-ea20e84352da.png)
![Fungi forest biome](https://user-images.githubusercontent.com/63923047/80911057-0cc0d000-8d34-11ea-9797-e02cef38b025.png)
![Undergarten biome](https://user-images.githubusercontent.com/63923047/80911058-10545700-8d34-11ea-94f4-3aa3ed57a184.png)
![Ruins mod structure](https://user-images.githubusercontent.com/63923047/80911061-134f4780-8d34-11ea-9ed0-7de73a0fb2e8.png)

(On the bottom of the minimap there is the name of the biome. To see how it should look like search the name in BOP wiki)

**Versions**
Chocolate Quest Repoured: Alpha 22
Forge: 1.12.2-14.23.5.2847
Minecraft: 1.12.2

**Other**
Crash report:
Log file:
Singleplayer
Other mods (that are necessary to produce the bug): CQR, BOP, ruins mod
Other mods (that are also installed): Agricraft, Baubles, Betterfps, Bibliocraft, Botania, Camping mod, ChunkAnimator, Clumps, CustomMobSpawner, Erebus, Foamfix, Forestry, GottschCore, Pam's Harvestcraft, Hwyla mod, iChun util, infinitylib, Just enough items, JourneyMap, Mantle, Metallurgy reforged, Milienaire mod, Mo'creatures, Optifine, phosphor lighting engine, PlantMegaPack, Radix core, Rikmuldscore, Surge, the Betweenlands mod, Tinkers construct, Treasure2, Tree Capitator, Twilight forest, Vanillafix, Waila harvestability, llibrary.

**Comment by DerToaster98** [comment] 2020-05-03 10:13
You do know that CQR isn't even able to cause bugs like this as it doesn't interfere with biome or dimension generation?
Also did you actually travel to the nether BEFORE installing CQR? If no, please confirm that the bugs are also present WITHOUT CQR, also check BOP first if that issue is present there.

Also this isn't reproduceable, it is caused by another mod or by a unstable version of BoP, i used the latest "Release" version for 1.12.2, nether biomes generate just fine for me.
![grafik](https://user-images.githubusercontent.com/38782719/80911588-7e4e4d80-8d37-11ea-83fe-a4c509729e47.png)

**Comment by DerToaster98** [comment] 2020-05-25 05:53
Issue will be closed as there was/is no reply from the creator of the issue

**Closed by DerToaster98** 2020-05-25 05:53 UTC
Labels: Bug in another mod, Not Reproduceable, Not a Bug
