### ISSUE TITLE
[1.12.2]Error installed with Wizardry

### ISSUE THREAD

**Issue by EnterFor** [TeamChocoQuest/ChocolateQuestRepoured#253] opened 2021-02-23 11:48 UTC
**Common sense Info**
To check a checkbox: Insert a lower case X between the square brackets, you need to remove the space though.
 - I play...
   - [ ] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x] Singleplayer
   - [x] Multiplayer
 - [x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x] I read through the FAQ and i could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [x] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured ('latest' IS NOT a valid version! Please use the version string that shows up in the mod overview of forge):
Forge:2855
Minecraft:1.12.2

**Describe the bug**
Install with Wizardry
There will be some errors
This can be found in the client log.
And I also tested with the server, the server can not enter

**To Reproduce**
1. Install Wizardry
2. Install Chocolate Quest Repoured
3. Start the game
.
.
.

**Expected behavior**
The server can go in

**Screenshots**
my mod list.Please ignore the Chinese characters
![image](https://user-images.githubusercontent.com/10114685/108839424-062b7e00-7610-11eb-87fb-cc1933c250c7.png)

**Other**
Please note: log files and crash reports should be uploaded as a FILE and not as a copy paste of the text of it here. Upload the file to a site like pastebin or similar and link it here!!
 - Link to Crash report file:
 - Link to Log file:https://paste.ubuntu.com/p/qmWcKSK3j7/  (Client log)
 - Other mods (that are necessary to produce the bug):
 - Other mods (that are also installed):https://www.curseforge.com/minecraft/mc-mods/wizardry-mod
 - CQR config folder (link, only if you changed the configs):
 - Other mod's configs (link):

**Comment by EnterFor** [comment] 2021-02-23 11:52
https://paste.ubuntu.com/p/p3yhXV8Qfn/   (server log)
The message that appears when the player tries to access the server

**Comment by DerToaster98** [comment] 2021-02-23 12:15
Can't reproduce it. I use CQR and wizardry in a small setup with a server and it works perfectly fine.

Also this doesn't seem to be a problem caused by eb-wizardry or cqr, there's no trace of either mod in the server log.

Also where did you download this from?

**Comment by DerToaster98** [comment] 2021-02-23 12:32
Ok, found the cause for the bug. Update will be released either later today or tomorrow, depends on when i test it.

**Comment by DerToaster98** [comment] 2021-02-23 12:37
Anyway, the fix i made only fixes a internal problem that occurs when a client *disconnects* from a server. I think the problem that you can't connect to a server has a different reason.
Also could it be that you use a pirated version of the game or a demo? Either that or your solution to host the server (which seems to be pretty strange for me) seems more likely to be the cause for your login problem.

**Comment by Meldexun** [comment] 2021-02-23 13:09
Looks like an incompatibility between librarianlib and bukkit. Are you able to join the server without cqr?

**Comment by EnterFor** [comment] 2021-02-23 13:18
> Looks like an incompatibility between librarianlib and bukkit. Are you able to join the server without cqr?

yes,I used to have a lot of mods, when I had problems, I started testing, and eventually found out that there would be errors when installing these two. Deleted CQR game continues normally

**Comment by EnterFor** [comment] 2021-02-23 13:19
My English is not very good, I use Google Translate.
Hope you can understand and thank you again for your quick reply!

**Comment by DerToaster98** [comment] 2021-02-23 13:24
Now then please just install CQR and llib. Can you still join with these two? And please try using the standard forge server, not some weird hybrid like magma/mohist/catserver

**Comment by EnterFor** [comment] 2021-02-23 13:36
Can you give me a fixed mod for me to test

**Comment by DerToaster98** [comment] 2021-02-23 13:43
Like i said, the fix i made only affects the game when you **disconnect** from the server. Honestly, the current release of the mod works fine for me. For forge's performance, there are some pretty decent mods that do a good job in that segment (phosphor, performant, betterFPS, etc)

**Comment by Meldexun** [comment] 2021-02-23 13:47
> - The issue occurs in...
> - [X] Singleplayer

You checked the singleplayer  checkbox. So can you reproduce this issue in singleplayer and then upload the log?
Also which server software are using?

**Comment by EnterFor** [comment] 2021-02-23 13:50
> > * The issue occurs in...
> > * [x]  Singleplayer
> 
> You checked the singleplayer checkbox. So can you reproduce this issue in singleplayer and then upload the log?
> Also which server software are using?
There are only error logs in the single player game. The game starts up normally.
As I posted earlier:
https://paste.ubuntu.com/p/qmWcKSK3j7/ (Client log)

**Comment by DerToaster98** [comment] 2021-02-23 13:56
And like i said: these errors occur when you disconnect from the server, they have nothing to do with login.

Anyways: I will release a cqr build later today that contains the changes i made. You can still try to compile it by yourself but you need to add geckolib-3-beta.7 to server & client

**Comment by EnterFor** [comment] 2021-02-23 13:58
I know, I finally understand this time

**Comment by EnterFor** [comment] 2021-02-23 14:00
Okey, I tested it with Forge server, and I didn't have any problems logging in, which is frustrating...

**Comment by EnterFor** [comment] 2021-02-23 14:01
> > * The issue occurs in...
> > * [x]  Singleplayer
> 
> You checked the singleplayer checkbox. So can you reproduce this issue in singleplayer and then upload the log?
> Also which server software are using?

I use the plugin
![image](https://user-images.githubusercontent.com/10114685/108854344-a917d400-75df-11eb-8cdd-3f0685f5de2d.png)

**Comment by DerToaster98** [comment] 2021-02-23 14:04
OK, then it seems to be mohist.

I can confirm you that 
1) There is a forge version of FAWE and worldedit
2) CQR (2.2.4B) works fine with the Magma Server software (i use it myself cause of bungeecord support)

**Comment by Meldexun** [comment] 2021-02-23 14:13
So I tested mohist and as I expected I can't connect when mohist and librarianlib is installed.
You should report this to librarianlib or mohist or both.

When only mohist, cqr and llibrary is installed it works fine.

**Comment by DerToaster98** [comment] 2021-02-23 14:15
OK, thank you meldex for confirming that CQR isn't the problem!

I will close the issue now.

@EnterFor Please report to mohist and librarianlib that they "don't like each other"

**Closed** 2021-02-23 14:16 UTC
Labels: Status: Working on it, Type: Bug, Waiting for feedback

**Comment by DerToaster98** [comment] 2021-02-24 08:51
maybe this helps you?
https://github.com/TeamWizardry/LibrarianLib/issues/129

liblib devs stated they don't support hybrid servers such as catserver, mohist, magma. So my guess is that you will have to use the standard forge server if you want to use mods that need liblib

**Comment by DerToaster98** [comment] 2021-02-24 08:52
this one contains a solution: https://github.com/Mohist-Community/Mohist/issues/659

Solution according to them is to add "-noverify" behind the "-jar" in your server-startup script

**Comment by EnterFor** [comment] 2021-02-24 08:57
Thank you so much. That's good news. I'll try it sometime.
Because now I've deleted LibrarianLib.
Thank you for your kindness! ~ღ( ´･ᴗ･` )

**Comment by EnterFor** [comment] 2021-02-24 09:01
I don't understand what this start parameter means.
What are some strange questions that arise?

**Comment by DerToaster98** [comment] 2021-02-24 09:20
Like i said, according to the mohist dev that is a solution to that problem.
I'd suggest you to just try it out.

Sinc that is a java launch argument, just check out the java documentation, it should be explained there.
