### ISSUE TITLE
1.12.2 small crash with Pixelmon

### ISSUE THREAD

**Issue by rebarakuk** [TeamChocoQuest/ChocolateQuestRepoured#319] opened 2022-01-10 17:45 UTC
**General Information**
To check a checkbox: Insert a X between the square brackets, you need to remove the space though.
 - I play...
   - [ x ] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [ x ] Singleplayer
   - [ ] Multiplayer
 - [ 1 ] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 - [ x ] I am using the latest version of the mod (all versions can be found on github under releases)
 - [ x ] I read through the FAQ and I could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [ ] The game crashes because of this bug
 

**Describe the bug**

When I right click the fruits of pixelmon on ground or to trees, this crash happens and the fruits aren't placed

**To Reproduce**
1. Go to ... the forest
2. Use item ...
3. Place block ... right click fruits of pixelmon on ground or to tress
4. ...

**Screenshots**
 

**Versions (Note that 'latest' is NOT a valid version!**
Chocolate Quest Repoured: Beta 6.5
Forge: 1.12.2 - 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): Pixelmon Reforged 8.3.5

**Log File**
Please use a paste site to upload the log file (for example https://gist.github.com/) and provide the link to the file here.

https://gist.github.com/rebarakuk/ddb916cf2f9335ded1db5b3077bc46d8

**Comment by Meldexun** [comment] 2022-01-10 17:50
Duplicate of #317
This was fixed in v1.12.2-2.6.4B

**Closed by Meldexun** 2022-01-10 17:50 UTC
Labels: Type: Bug
