### ISSUE TITLE
Crash when on Better questing item selection Gui for too long. (due to dungeon placers)

### ISSUE THREAD

**Issue by Darkmega18** [TeamChocoQuest/ChocolateQuestRepoured#159] opened 2020-03-19 08:28 UTC
**Describe the bug**
As the name says, I am making a pack, and i was just having the mod in to have a trip down memory lane _(due to it's relation to certain things in this pack and a past packs from 1.6.4 I had made)_ when I stop working on quests etc _(I haven't used anything from CQ yet in quests etc due to it's alpha state. don't worry..)_ 

But when I'm writing my quests and I'm on the Item selection gui to add rewards or task items or select icons for various quests if I linger too long on the page without searching for something or getting off it, presumeably when it gets to the point of picking up on CQ's items _(apparently the dungeon placers)_ it crashes and gives me the attached crash log and sends me to main menu thanks to vanilla fix.

**To Reproduce**
Install Better questing and chocolate quest.
Activate edit mode
Make a quest and try to change the icon or add an item to a task or rewards.
Wait for it to crash after a few seconds. (Probably a lot faster without all my other things in the way)

**Expected behavior**
should be just fine like all the other items so far.

**Versions**
Chocolate Quest Repoured: ChocolateQuestRepoured-1.12.2-1.12.1A.jar
Forge: forge-14.23.5.2847
Minecraft: 1.12.2

**Singleplayer/Multiplayer:** Singleplayer

**Other mods (that are necessary to produce the bug):** Better questing, as far as I know.

**Other mods (that are also installed):** A lot. See crash report print out... :V

**_Latest log and crash report as of that load up._**
[latest.log](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4353377/latest.log)
[crash-2020-03-19_19.16.07-client.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/4353379/crash-2020-03-19_19.16.07-client.txt)

**Comment by DerToaster98** [comment] 2020-03-19 08:52
i highly doubt that this is caused by CQR alone. From the code i see that something passes CQR null for the itemstack OR its nbt. CQR then runs into an NPE and crashes. I added a non-null check on the NBT compound. if it still doesnt work in the next build, please contact the dev of better questing to come here and help with patching this bug

**Comment by DerToaster98** [comment] 2020-03-19 08:59
Will be fixed in next build. tested my changes, it doesnt crash

**Closed by DerToaster98** 2020-03-19 08:59 UTC
Labels: Type: Bug

**Comment by DerToaster98** [comment] 2020-03-19 21:50
is fixed in newest version

**Comment by Darkmega18** [comment] 2020-03-20 08:13
thank you for the fast response and fix. I'll take a look after I complete some more work on the mechanics and stuff in the pack and when I go to actually just play the thing for a bit. :)
