### ISSUE TITLE
Possible Conflict (Entity Ticking Crash)

### ISSUE THREAD

**Issue by Fooshcookie** [TeamChocoQuest/ChocolateQuestRepoured#237] opened 2020-12-23 09:27 UTC
**Common sense Info**
 - I play...
   - [x] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [x] Singleplayer
   - [ ] Multiplayer
 - [x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x] I read through the FAQ and i could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [x] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured: 2.1.3B 
Forge: 14.23.5.2855
Minecraft: 1.12.2 Forge

**Describe the bug**
A seeming conflict (I believe, so don't quote me on it) with the AI changes of Dynamic Stealth to CQR seems to cause the ticking entity crash. I'm unable to pin-point the action the enemies are attempting to take that causes the crash. Upon removing Dynamic Stealth, the issue seemed to stop, this was after reproducing it twice while both mods we're enabled on the modpack. Reproduced again on a clean version of forge profile with only the two mods (and respected libraries). I will be providing the logs and report of both of the instances.

I will be clear, I am not sure if it is Dynamic Stealth causing it, it just -seems- based on testing to be the culprit. If it does turn out to be a conflict, I'm not 100% sure which end this is on, I'm taking it's on the Dynamic Stealth end, however I can't be sure. I'm not familiar with java in terms of code, so, I just am going to play it safe by bringing it to you guys first, just in-case. Hope it's not too much a bother, in the end, love the work. <3

The Necromancer typed bosses are confirmed to cause the crash, also tested against Skeletons which also resulted in the crash. I'm unsure of everything else, however Walker King does not seem to cause this. As I'm writing, I do believe it is likely ranged related, which I believe the log hint at, however as before, I have no clue what I'm talking about.

Will be linking the configs for both mods, regardless, as I can't recall if I changed any configs. I think I changed a generation config due to a crash it was producing, which I believe is already being fixed on another post. I can elaborate on this if it is needed, but this is unrelated to my crashes.

If anything else is needed, I will be checking back in here when I can.

**To Reproduce**
1. Go to any CQR dungeon with CQR and Dynamic Stealth enabled.
2. Attack CQR enemies until the crash happens. 
3. Crash due to entity ticking.

**Expected behavior**
Expected result is to not crash while engaged in combat.

**Screenshots**
No Screenshots Applicable

**Other**
Please note: log files and crash reports should be uploaded as a FILE and not as a copy paste of the text of it here. Upload the file to a site like pastebin or similar and link it here!!
 - Link to Modpack Crash report file: https://pastebin.com/KHwCjXKq
 - Link to Singled Out Crash report file: https://pastebin.com/f1s87Kdh
 - Link to Singled Out Log file: https://pastebin.com/cPaXdyqd
 - Other mods (that are necessary to produce the bug): Dynamic Stealth (Presumably)
 - Other mods (that are also installed): Many in Modpack Instance, None in Singled Out
 - CQR config folder (link, only if you changed the configs): https://drive.google.com/drive/folders/17RN7bmHd_wAQYp7TywEw_s7Wj6ePIylu?usp=sharing
 - Other mod's configs (link): https://drive.google.com/drive/folders/1wGBksDQj8tpHN2tS9B3RODLs8qNIYl-_?usp=sharing

**Comment by DerToaster98** [comment] 2020-12-23 10:37
OK, it seems like DynamicStealth does some dirty stuff here, cause the issue is caused by something setting the attackTarget of the AI to null, which by default can't be null at that point cause it was checked beforehand. 

So i guess it is dynamic stealth setting it to null here, which is not good style.
We can fix it on our end but i don't think that it is just cqr and it's ranged AI that is conflicting, i will contact the dynamic stealth dev to figure out if they really set fields to null.

Will be fixed in the next patch.

**Comment by DerToaster98** [comment] 2020-12-23 12:01
Correction: The problem was on our end, we seem to have overseen the Nullable flag on one of the methods and didn't check for null, should still be fixed in the next patch version

**Comment by Fooshcookie** [comment] 2020-12-23 22:09
Excellent! I will hold off further work on the modpack until the next patch, or just disable Dynamic Stealth until then. I'll let you know if I encounter anymore bugs. Thanks for the help. 👍🏻

**Comment by DerToaster98** [comment] 2021-01-05 18:32
We published a new release today, please test if the issue still exists.

**Closed** 2021-01-29 14:02 UTC
Labels: Priority: Low, Status: Working on it, Type: Bug, Waiting for feedback
