### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by LUEZIS** [TeamChocoQuest/ChocolateQuestRepoured#197] opened 2020-06-03 09:54 UTC
**Common sense Info**
 - I play...
   - [x] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [ ] Singleplayer
   - [ ] Multiplayer
 - [ ] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [x] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured: 1.12.2-1.19.0A
Forge: 14.23.5.2854
Minecraft: normal, premium kek, 1.12.2

**Describe the bug**

Just crash on startup, idk.

**To Reproduce**
2. Use item '....'
3. Place block '....'
.
.
.

**Expected behavior**

**Screenshots**

**Other**
Please note: log files and crash reports should be uploaded as a FILE and not as a copy paste of the text of it here. Upload the file to a site like pastebin or similar and link it here!!
 - Link to Crash report file: https://pastebin.com/6mvwz7rM
 - Link to Log file:
 - Other mods (that are necessary to produce the bug):
 - Other mods (that are also installed):
 - CQR config folder (link, only if you changed the configs):
 - Other mod's configs (link):

**Comment by DerToaster98** [comment] 2020-06-03 09:59
won't be worked on until it is reproduced with only cqr installed. also it is more a problem with your system, you probably set the CQR folder to read only or you marked the cqr jar as read only

**Comment by guitarpick38** [comment] 2020-06-03 10:20
I had the same issue with just CQR installed. It's caused by the CQR folder being read only by default which also causes no files to appear in any of the subfolders. 
Deselecting read only on the CQR folder then loading the game again makes the folder reselect the read only option.

**Comment by DerToaster98** [comment] 2020-06-03 10:21
actually we don't even set these attributes to the folder

**Comment by DerToaster98** [comment] 2020-06-03 10:53
fixed in newest version

**Closed by DerToaster98** 2020-06-03 10:53 UTC
Labels: Layer 8, Type: Invalid
