### ISSUE TITLE
V6.2B Crashes Client on MAC OS Only

### ISSUE THREAD

**Issue by RupticMC** [TeamChocoQuest/ChocolateQuestRepoured#306] opened 2021-12-12 18:23 UTC
**Common sense Info**
To check a checkbox: Insert a lower case X between the square brackets, you need to remove the space though.
 - I play...
   - [x] With a large modpack
   - [ ] Only with CQR and it's dependencies
 - The issue occurs in...
   - [ ] Singleplayer
   - [ ] Multiplayer
   - [x] On Boot
 - [x] I have searched for this or a similar issue before reporting and it was either (1) not previously reported, or (2) previously fixed  and I'm having the same problem.
 - [x] I am using the latest version of the mod (all versions can be found on github under releases)
 - [x] I read through the FAQ and i could not find something helpful ([FAQ](https://wiki.cq-repoured.net/index.php?title=FAQ))
 - [ ] I reproduced the bug without any other mod's except forge, cqr and it's dependencies
 - [x] The game crashes because of this bug
 
 
 **Versions**
Chocolate Quest Repoured ('latest' IS NOT a valid version! Please use the version string that shows up in the mod overview of forge): Chocolate_Quest_Repoured-1.12.2-2.6.2B
Forge: 2859
Minecraft: 1.12.2

**Describe the bug**
While launching the mod on the Chaotic Crusade mod pack v6.2B, it causes the client to crash only on a MAC. Multiple people in my community has tested this on their MAC and has caused their Minecraft client to crash.

**To Reproduce**
1. Use CQ 6.2B on a MAC with forge 2859

**Expected behavior**
To completely boot to the main menu instead of crashing.

**Screenshots**
N/A

**Other**
Please note: log files and crash reports should be uploaded as a FILE and not as a copy paste of the text of it here. Upload the file to a site like pastebin or similar and link it here!!
 - Link to Crash report file (only if the game crashes because of this bug, please use something like pastebin to upload it, then link it here): https://pastebin.com/F6AtjDwr
 - Link to Log file (only if the game crashes because of this bug, please use something like pastebin to upload it, then link it here):
 - Other mods (that are necessary to produce the bug):
 - Other mods (that are also installed, at best: link a zip file that contains all the installed mods): https://paste.helpch.at/koqanuhumo.cs
 - CQR config folder (link, only if you changed the configs):
 - Other mod's configs (link, only if any config was changed):
 
 
 **Extra Notes**
1. AnthonySlasher has also reported this issue over on the MinecraftForge website.  https://forums.minecraftforge.net/topic/106555-i-have-tried-to-run-forge-1122-but-it-crashes-with-an-unexpected-error-please-help-the-records-are-here/

2. Used to work fine with Chocolate_Quest_Repoured-1.12.2-**2.5.3B**

**Comment by DerToaster98** [comment] 2021-12-12 18:25
We already know of this issue. 

It only works with 2.5.3B cause the shader causing the crash wasn't added there yet.

**Comment by DerToaster98** [comment] 2021-12-12 18:26
Duplicate of #302

**Closed by DerToaster98** 2021-12-12 18:26 UTC
Labels: Type: Bug
